name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Create a new release
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/tags/}"
          RELEASE_FILE="${{ github.event.repository.name }}-$RELEASE_TAG.tar.gz"
          RELEASE_FILE_TMP="/tmp/$RELEASE_FILE"

          tar -czf "$RELEASE_FILE_TMP" --exclude='.git' --exclude='.github' --exclude='.gitignore' -C "${{ github.workspace }}" .
          gh release create "$RELEASE_TAG" "$RELEASE_FILE_TMP" --generate-notes
        env:
          GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
